### ISSUE TITLE
Unable to Launch Spotify

### ISSUE THREAD

**Issue by GamerClassN7** [TheRandomLabs/Scoop-Bucket#2]
Hi,
every time i try to install spotify-lastes 

i am stuck in update after first run.

![image](https://user-images.githubusercontent.com/22167469/77298341-172a8b80-6ceb-11ea-8d77-133bd28f0bf3.png)

Did anyone have same problem  ?

**Comment by TheRandomLabs** [comment]
Have you made sure to uninstall Spotify first?

**Comment by GamerClassN7** [comment]
Yes

**Comment by GamerClassN7** [comment]
i have another info, when i install original Spotify and uninstall it via bulcrapUninstaller and then install it from scoop i run but only once when i close it and reopen i am stuck on same error. Updating Spotify

**Comment by TheRandomLabs** [comment]
If you download the [installer](http://download.spotify.com/SpotifyFullSetup.exe) manually and run `SpotifyFullSetup /extract [dir]`, what happens?

**Comment by GamerClassN7** [comment]
spotify is extracted to specified folder, and is fully working  :)

**Comment by TheRandomLabs** [comment]
Interesting, that means something's wrong with the manifest...

**Comment by GamerClassN7** [comment]
if i modify manifest like this it seems to work 
`"New-Item \"$env:APPDATA\\Spotify\" -ItemType \"directory\" | Out-Null",
            "New-Item \"$env:APPDATA\\Spotify\\Update\" -ItemType \"directory\"",
            "icacls \"$env:APPDATA\\Spotify\\Update\" \"/deny\" \"$($env:UserName):D\"",
            "icacls \"$env:APPDATA)\\Spotify\\Update\" \"/deny\" \"$($env:UserName):R\""`

**Comment by TheRandomLabs** [comment]
That would prevent updates from occurring, but that doesn't explain why updates aren't working in the first place.

**Comment by GamerClassN7** [comment]
@TheRandomLabs  yes, but i guess it is ok because i update app thru scoop

**Comment by AlJohri** [comment]
I'm running into the same issue with the updates not working.

@GamerClassN7 if you update Spotify through scoop, does it log you out every time you update?

**Comment by TheRandomLabs** [comment]
You're not meant to update `spotify-latest` through Scoop; it's meant to auto-update itself. I'll take a look at the manifest again when I get a chance.

**Comment by GamerClassN7** [comment]
> I'm running into the same issue with the updates not working.
> 
> @GamerClassN7 if you update Spotify through scoop, does it log you out every time you update?

No i autoupdate all app from scoop :)

**Comment by TheRandomLabs** [comment]
With the recent introduction of the `checkver.script` property, `spotify-latest` no longer has to be `nightly`. Since `spotify-latest` can now be updated through Scoop, I've been able to make several improvements, and this issue is now resolved. :)

**Comment by TheRandomLabs** [comment]
I would recommend reinstalling `spotify-latest` by running `scoop update -f spotify-latest`.
